# Generated by Django 5.0.6 on 2024-06-17 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
