# Generated by Django 5.0.6 on 2024-06-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_booking_room_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=1000),
        ),
    ]
