# Generated by Django 5.0.6 on 2024-06-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_booking_number_alter_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AddField(
            model_name='booking',
            name='garden_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
