# Generated by Django 5.0.6 on 2024-06-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_rename_garden_id_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bid',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
